DROP DATABASE IF EXISTS db_dietetica;

CREATE DATABASE db_dietetica ;

USE db_dietetica ;

-- Tabla PEDIDO
CREATE TABLE PEDIDO (
  IDPedido INT PRIMARY KEY AUTO_INCREMENT,
  Fecha DATE,
  Total DECIMAL(10, 2),
  IDCliente INT,
  IDProducto INT,
  IDMetodoPago INT
);

-- Tabla FACTURA
CREATE TABLE FACTURA (
  IDFactura INT PRIMARY KEY AUTO_INCREMENT,
  Fecha DATE,
  Total DECIMAL(10, 2),
  IDPedido INT
);

-- Tabla PRODUCTO
CREATE TABLE PRODUCTO (
  IDProducto INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(100),
  Descripcion TEXT,
  PrecioVenta DECIMAL(10, 2),
  PrecioCosto DECIMAL(10, 2),
  StockActual INT,
  StockMinimo INT,
  IDProveedor INT,
  IDCategoria INT
);

-- Tabla CLIENTE
CREATE TABLE CLIENTE (
  IDCliente INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(100) DEFAULT 'USUARIO_NO_EXISTE',
  Telefono VARCHAR(20) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  Direccion VARCHAR(200)
);

-- Tabla PROVEEDOR
CREATE TABLE PROVEEDOR (
  IDProveedor INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(100),
  Direccion VARCHAR(200),
  Telefono VARCHAR(20),
  Email VARCHAR(100)
);

-- Tabla METODO_DE_PAGO
CREATE TABLE METODO_DE_PAGO (
  IDMetodoPago INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(100),
  Descripcion TEXT
);

-- Tabla CATEGORIA_PRODUCTO
CREATE TABLE CATEGORIA_PRODUCTO (
  IDCategoria INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(100),
  Descripcion TEXT
);

-- FOREING KEYS DEFINITION

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PEDIDO_CLIENTE
FOREIGN KEY (IDCliente) REFERENCES CLIENTE(IDCliente);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_METODO_DE_PAGO_CLIENTE
FOREIGN KEY (IDMetodoPago) REFERENCES METODO_DE_PAGO(IDMetodoPago);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PRODUCTO_PEDIDO
FOREIGN KEY (IDProducto) REFERENCES PRODUCTO(IDProducto);

ALTER TABLE FACTURA
ADD CONSTRAINT FK_FACTURA_PEDIDO
FOREIGN KEY (IDPedido) REFERENCES PEDIDO(IDPedido);

ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_PROVEEDOR
FOREIGN KEY (IDProveedor) REFERENCES PROVEEDOR(IDProveedor);
 
ALTER TABLE PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_CATEGORIA
FOREIGN KEY (IDCategoria) REFERENCES CATEGORIA_PRODUCTO(IDCategoria);
